// src/apps/angular/notepad.app.ts
import { Component, signal } from '@angular/core';

@Component({
  selector: 'bliss-notepad',
  standalone: true,
  styles: [
    `
      :host {
        display: flex;
        flex-direction: column;
        height: 100%;
        background: #fff;
      }
      textarea {
        flex: 1;
        border: 0;
        outline: none;
        resize: none;
        padding: 10px 12px;
        font-family: 'Consolas', 'Lucida Console', monospace;
        font-size: 0.95rem;
        line-height: 1.45;
        color: #1a1a1a;
      }
      .status {
        border-top: 1px solid #d6d2c4;
        background: #ece9d8;
        padding: 2px 8px;
        font: 0.72rem Tahoma, sans-serif;
        color: #555;
        text-align: right;
      }
    `,
  ],
  template: `
    <textarea
      data-testid="notepad-text"
      [value]="text()"
      (input)="onInput($event)"
      spellcheck="false"
      placeholder="Type here…"
    ></textarea>
    <div class="status">{{ text().length }} chars</div>
  `,
})
export class NotepadApp {
  readonly text = signal('');
  onInput(e: Event): void {
    this.text.set((e.target as HTMLTextAreaElement).value);
  }
}

// src/apps/react/NotepadApp.tsx
import { useState } from 'react';

export function NotepadApp() {
  const [text, setText] = useState(
    'Welcome to Bliss OS Notepad.\n\nThis window is rendered by React.\nThe Calculator and File Explorer are rendered by Angular.\n\nTry dragging a window — it wobbles.',
  );
  const words = text.trim() ? text.trim().split(/\s+/).length : 0;

  return (
    <div
      style={{
        display: 'flex',
        flexDirection: 'column',
        height: '100%',
        background: '#fff',
        fontFamily: 'Tahoma, "Segoe UI", sans-serif',
      }}
    >
      <textarea
        data-testid="notepad-text"
        value={text}
        onChange={(e) => setText(e.target.value)}
        spellCheck={false}
        style={{
          flex: 1,
          border: 'none',
          outline: 'none',
          resize: 'none',
          padding: '8px 10px',
          font: '0.95rem/1.5 Consolas, monospace',
          color: '#111',
        }}
      />
      <div
        style={{
          borderTop: '1px solid #adacac',
          background: '#ece9d8',
          padding: '3px 10px',
          fontSize: '0.78rem',
          color: '#444',
        }}
      >
        {words} words · {text.length} chars
      </div>
    </div>
  );
}
