// src/app/taskbar.component.ts
import { Component, computed, inject } from '@angular/core';
import { APPS } from '../ng/app-registry';
import { WindowStore } from '../ng/window-store';

/** XP-style taskbar: Start button, one button per open window, and a clock. */
@Component({
  selector: 'app-taskbar',
  standalone: true,
  template: `
    <div class="taskbar">
      <button class="start-button" data-testid="start-button">
        <span class="start-button__logo" aria-hidden>⊞</span>
        start
      </button>
      <div class="taskbar__tasks">
        @for (w of store.windows(); track w.id) {
          <button
            class="task"
            [class.task--active]="w.focused"
            data-testid="task-button"
            [attr.data-appid]="w.appId"
            (click)="store.focus(w.id)"
          >
            <span aria-hidden>{{ w.icon }}</span>
            <span class="task__label">{{ w.title }}</span>
          </button>
        }
      </div>
      <div class="taskbar__launchers">
        @for (a of apps; track a.id) {
          <button
            class="task"
            data-testid="launcher"
            [attr.data-appid]="a.id"
            [title]="a.title"
            (click)="store.openOrFocus(a.id)"
          >
            <span aria-hidden>{{ a.icon }}</span>
          </button>
        }
      </div>
      <div class="systray"><span class="clock" data-testid="clock">{{ clock() }}</span></div>
    </div>
  `,
})
export class TaskbarComponent {
  readonly store = inject(WindowStore);
  readonly apps = APPS;
  readonly clock = computed(() => {
    const d = new Date();
    return `${((d.getHours() + 11) % 12) + 1}:${String(d.getMinutes()).padStart(2, '0')}`;
  });
}

// src/shell/Taskbar.tsx
import { useWindowStore } from '../core/windowStore';
import { APPS, getApp } from '../core/appRegistry';
import { SystemTray } from './SystemTray';

export function Taskbar({
  startOpen,
  onToggleStart,
}: {
  startOpen: boolean;
  onToggleStart: () => void;
}) {
  const windows = useWindowStore((s) => s.windows);
  const running = useWindowStore((s) => s.running);
  const openOrFocus = useWindowStore((s) => s.openOrFocus);
  const minimize = useWindowStore((s) => s.minimize);

  // One entry per running app (registry order), including windowless ones.
  const entries = APPS.filter((a) => running[a.id]).map((a) => {
    const wins = windows.filter((w) => w.appId === a.id);
    const top = wins.length
      ? wins.reduce((x, y) => (x.z >= y.z ? x : y))
      : null;
    const active = !!top && top.focused && !top.minimized;
    return { appId: a.id, hasWindow: wins.length > 0, top, active };
  });

  return (
    <div className="taskbar">
      <button
        className={`start-button${startOpen ? ' start-button--active' : ''}`}
        onClick={onToggleStart}
        data-testid="start-button"
      >
        <span className="start-button__logo" aria-hidden>
          ⊞
        </span>
        start
      </button>

      <div className="taskbar__tasks">
        {entries.map(({ appId, top, active }) => {
          const app = getApp(appId);
          return (
            <button
              key={appId}
              className={`task${active ? ' task--active' : ''}`}
              data-testid="task-button"
              data-appid={appId}
              onClick={() =>
                active && top ? minimize(top.id) : openOrFocus(appId)
              }
            >
              <span className="task__dot" aria-hidden />
              <span aria-hidden>{app?.icon}</span>
              <span className="task__label">{app?.title}</span>
            </button>
          );
        })}
      </div>

      <SystemTray />
    </div>
  );
}
